version: '3.8'

services:
  app:
    image: tommy1964/springboot-app:1.0
    ports:
      - 8080:8080
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/manytoone
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - springboot-mysql-network

  mysqldb:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=manytoone
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqlData:/var/lib/mysql
    networks:
      - springboot-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

  flutter-web-app:
    image: tommy1964/flutter-web-app:1.0
    container_name: manytoone-flutter-web-app
    ports:
      - "1200:80"
    networks:
      - springboot-mysql-network

volumes:
  mysqlData:

networks:
  springboot-mysql-network:
    name: springboot-mysql-network
